### ISSUE TITLE
Header en resolucion alta no se centra

### ISSUE THREAD

**Issue by MiltonC3** [MDMendez1207/Clase-17DDHH#1]
-Podrias sacar el width fijo o poner un width 100%

![image](https://github.com/MDMendez1207/Clase-17DDHH/assets/87451298/7a5691f2-8d8b-42d7-a3b5-872d1fabce77)

**Comment by MDMendez1207** [comment]
Centré las cosas, para que a pesar de que no ocupe todo el ancho de la pantalla, no quede tan mal
